### ISSUE TITLE
document how to configure clasp dev environment

### ISSUE THREAD

**Issue by allenday** [blockchain-etl/data-studio-connectors#3]
```
$ npm run push

> @ push /Users/allenday/src/google/data-studio-connectors/crypto-analytics
> dscc-scripts connector push_changes


No valid .clasp.json project file. You may need to `create` or `clone` a project first.
Command failed: npx @google/clasp push
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ push: `dscc-scripts connector push_changes`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ push script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by allenday** [comment]
I updated the README with a link for how to init the `.clasp.json` file, but I'm not sure if this solves the problem, as `npm run try_latest` still fails. 

It is not clear where the connectorId is defined. See attached screenshot:

<img width="578" alt="Screen Shot 2020-08-18 at 2 17 27 PM" src="https://user-images.githubusercontent.com/436031/90477313-c4e87c00-e15d-11ea-8f50-db83474f0f46.png">

**Comment by franckc** [comment]
Ah sorry, my bad for not adding more details.

Following these steps should fix the issue:
https://developers.google.com/datastudio/connector/local-development

I'll try on a fresh git clone to make sure it works and will update the README accordingly.

**Comment by allenday** [comment]
thanks - this is still not enough detail and I'm thrashing trying to get it to integrate. not clear do I need to pre-create the project and copy scriptId in, or if I should create fresh with dscc-gen.

**Comment by allenday** [comment]
I'll stop work now. FYI the readme should be considered inaccurate and needs to be QAed, my edits are not correctly setting up the env, I keep getting stuck on this scriptId issue on `npm try try_latest`

**Comment by franckc** [comment]
Got it. Yep, let me clean this up. Will ping this thread once I've had a chance to try the whole setup from fresh...
